apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.grafana.volume.storage.name }}"
  namespace: "{{ .Values.grafana.namespace }}"
spec:
  accessModes:
    - "{{ .Values.grafana.volume.storage.accessMode }}"
  resources:
    requests:
      storage: "{{ .Values.grafana.volume.storage.size }}"
