apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.traefik.name }}"
  namespace: "{{ .Values.traefik.namespace }}"

spec:
  externalTrafficPolicy: "{{ .Values.traefik.service.externalTrafficPolicy }}"
  ports:
    - protocol: "{{ .Values.traefik.service.ports.protocol }}"
      name: "{{ .Values.traefik.service.ports.web.name }}"
      port: {{ .Values.traefik.service.ports.web.port }}
    - protocol: "{{ .Values.traefik.service.ports.protocol }}"
      name: "{{ .Values.traefik.service.ports.websecure.name }}"
      port: {{ .Values.traefik.service.ports.websecure.port }}
    - protocol: "{{ .Values.traefik.service.ports.protocol }}"
      name: "{{ .Values.traefik.service.ports.admin.name }}"
      port: {{ .Values.traefik.service.ports.admin.port }}
  selector:
    app: "{{ .Values.traefik.name }}"
  sessionAffinity: "{{ .Values.traefik.service.sessionAffinity }}"
  type: "{{ .Values.traefik.service.type }}"
status:
  loadBalancer: {}
