apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Values.traefik.cron.name }}"
  namespace: "{{ .Values.traefik.namespace }}"
spec:
  schedule: "{{ .Values.traefik.cron.schedule }}"
  concurrencyPolicy: "{{ .Values.traefik.cron.concurrency }}"
  successfulJobsHistoryLimit: {{ .Values.traefik.cron.successHistory }}
  failedJobsHistoryLimit: {{ .Values.traefik.cron.failHistory }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "{{ .Values.traefik.cron.restart }}"
          containers:
            - name: "{{ .Values.traefik.cron.name }}"
              image: "{{ .Values.traefik.cron.image }}"
              imagePullPolicy: "{{ .Values.traefik.cron.pullPolicy }}"
              env:
              - name: "{{ .Values.traefik.env.api.name }}"
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.traefik.env.api.secretName }}"
                    key: "{{ .Values.traefik.env.api.name }}"
              command: [{{- join "," .Values.traefik.cron.command }}]
              volumeMounts:
                - name: "{{ .Values.traefik.cron.volume.name }}"
                  mountPath: "{{ .Values.traefik.cron.volume.mountPath }}"
          volumes:
            - name: "{{ .Values.traefik.cron.volume.name }}"
              configMap:
                name: "{{ .Values.traefik.cron.name }}"
                defaultMode: {{ .Values.traefik.cron.volume.mode }}
